2019-11-21 16:03:33,893 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-11-26 12:22:46,377 - __main__ - WARNING - Update "{'update_id': 62101517, 'message': {'message_id': 269, 'date': 1574770966, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/help', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 5}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 269, 'date': 1574770966, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/help', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 5}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "[Errno 5] Input/output error"
2019-11-28 15:23:31,320 - telegram.ext.updater - INFO - Received signal 15 (SIGTERM), stopping...
2019-11-28 15:31:07,857 - __main__ - WARNING - Cannot establish group type supergroup
2019-11-28 15:32:24,787 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-11-28 15:44:44,367 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-02 10:11:23,493 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-02 10:12:13,636 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-11 21:28:06,190 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-11 21:30:48,618 - __main__ - WARNING - Update "{'update_id': 62101535, 'message': {'message_id': 298, 'date': 1576099848, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 298, 'date': 1576099848, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "invalid literal for int() with base 10: ''"
2019-12-11 21:30:56,022 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-11 21:31:01,548 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-11 21:40:58,916 - __main__ - WARNING - Update "{'update_id': 62101537, 'message': {'message_id': 302, 'date': 1576100458, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 302, 'date': 1576100458, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "name 'user_id' is not defined"
2019-12-11 21:41:13,952 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-11 21:42:45,892 - __main__ - WARNING - Update "{'update_id': 62101539, 'message': {'message_id': 306, 'date': 1576100565, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 306, 'date': 1576100565, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "name 'user_id' is not defined"
2019-12-11 21:42:52,376 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-11 21:45:43,470 - __main__ - WARNING - Update "{'update_id': 62101541, 'message': {'message_id': 310, 'date': 1576100743, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 310, 'date': 1576100743, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "name 'user_id' is not defined"
2019-12-11 21:45:46,231 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-11 21:45:46,232 - __main__ - WARNING - Update "{'update_id': 62101542, 'message': {'message_id': 312, 'date': 1576100746, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/deactivate', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 11}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 312, 'date': 1576100746, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/deactivate', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 11}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "module 'os' has no attribute 'exit'"
2019-12-11 21:46:01,638 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-11 21:47:22,408 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-11 21:47:36,274 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-11 21:48:22,139 - telegram.ext.updater - WARNING - Exiting immediately!
2019-12-11 21:51:47,788 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-11 21:52:09,014 - telegram.ext.updater - WARNING - Exiting immediately!
2019-12-11 21:53:58,838 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-11 21:54:13,830 - telegram.ext.updater - WARNING - Exiting immediately!
2019-12-11 21:54:23,496 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-11 21:54:23,835 - telegram.ext.updater - WARNING - Exiting immediately!
2019-12-11 21:57:25,783 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-11 21:57:36,170 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-11 21:57:36,966 - telegram.ext.updater - WARNING - Exiting immediately!
2019-12-11 21:58:13,988 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-21 15:50:19,064 - __main__ - WARNING - Update "{'update_id': 62101552, 'message': {'message_id': 333, 'date': 1576943419, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/help', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 5}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 333, 'date': 1576943419, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/help', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 5}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "invalid literal for int() with base 10: ''"
2019-12-21 15:50:31,328 - __main__ - WARNING - Update "{'update_id': 62101554, 'message': {'message_id': 337, 'date': 1576943431, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/help', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 5}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 337, 'date': 1576943431, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/help', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 5}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "invalid literal for int() with base 10: ''"
2019-12-21 15:50:55,139 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-21 15:56:37,168 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-21 16:17:27,346 - __main__ - WARNING - Update "{'update_id': 62101564, 'message': {'message_id': 357, 'date': 1576945047, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 357, 'date': 1576945047, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "Object of type timedelta is not JSON serializable"
2019-12-21 16:17:34,295 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-21 16:17:34,481 - telegram.ext.updater - WARNING - Exiting immediately!
2019-12-21 16:22:38,153 - __main__ - WARNING - Update "{'update_id': 62101565, 'message': {'message_id': 359, 'date': 1576945358, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}, '_effective_user': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}, '_effective_chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, '_effective_message': {'message_id': 359, 'date': 1576945358, 'chat': {'id': 1009602212, 'type': 'private', 'username': 'LordBenAtkinson', 'first_name': 'Ben', 'last_name': 'Atkinson'}, 'text': '/christmas', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 10}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1009602212, 'first_name': 'Ben', 'is_bot': False, 'last_name': 'Atkinson', 'username': 'LordBenAtkinson', 'language_code': 'en'}}}" caused error "'datetime.timedelta' object has no attribute 'hours'"
2019-12-21 16:22:50,883 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-21 16:22:51,060 - telegram.ext.updater - WARNING - Exiting immediately!
2019-12-21 16:26:03,752 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-21 16:26:03,928 - telegram.ext.updater - WARNING - Exiting immediately!
2019-12-21 16:27:12,521 - __main__ - CRITICAL - Shutdown initiated by Ben:Atkinson:1009602212
2019-12-21 20:05:17,366 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-12-21 20:05:17,901 - telegram.ext.updater - WARNING - Exiting immediately!
